name: sounds
version: 1.0.0-beta13
homepage: https://github.com/bsutton/sounds
documentation: https://github.com/bsutton/sounds/wiki
description: Sounds provide a complete api and Widgets for audio playback and recording. Both iOS and Android are supported.
repository: https://github.com/bsutton/sounds
environment: 
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.20.0 <3.0.0'
dependencies: 
  dart_native: ^0.3.4
  dart_numerics: ^0.0.5
  device_info: '>=0.4.2+4 <2.0.0'
  flutter_spinkit: ^4.0.0
  meta: ^1.1.8
  path: ^1.6.4
  path_provider: ^1.6.7
  provider: ^4.1.0
  sounds_common: #^1.0.0
    path: ../sounds_common
  sounds_platform_interface:
    path: ../sounds_platform_interface
  test:
  uuid: ^2.0.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.9.0
  effective_dart: ^1.2.1
  dcli: ^0.33.0
  e2e: ^0.7.0
  lint: ^1.1.1
  pub_semver: ^1.4.4
  pigeon: 0.1.10
    #path: ../../packages/packages/pigeon

  flutter_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: 
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin: 
    platforms: 
      android: 
        package: com.bsutton.sounds
        pluginClass: SoundsPlugin
      ios:
        pluginClass: SoundsPlugin
