name: sounds
version: 0.8.2
homepage: https://github.com/bsutton/sounds
description: Sounds provide a complete api and Widgets for audio playback and recording. Both iOS and Android are supported.
environment: 
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  effective_dart: ^1.2.1
  ext_storage: ^1.0.3
  flutter_spinkit: ^4.0.0
  intl: ^0.16.1
  logger: ">=0.7.0+2 <1.0.0"
  path_provider: ^1.6.7
  path: ^1.6.4
  pedantic: ^1.9.0
  provider: ^4.1.0
  uuid: ^2.0.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  dshell: ^1.0.0
  e2e: ^0.5.0
  lint: ^1.1.1
  pub_semver: ^1.4.4
  flutter_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.bsutton.sounds
        pluginClass: Sounds
      ios: 
        pluginClass: Sounds
