name: sounds
version: 0.8.9
homepage: https://github.com/bsutton/sounds
description: Sounds provide a complete api and Widgets for audio playback and recording. Both iOS and Android are supported.
environment: 
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_spinkit: ^4.0.0
  path_provider: ^1.6.7
  provider: ^4.1.0
  
  uuid: ^2.0.4

dev_dependencies: 
  pedantic: ^1.9.0
  effective_dart: ^1.2.1
  dshell: ^1.0.0
  e2e: ^0.5.0
  lint: ^1.1.1
  pub_semver: ^1.4.4
  flutter_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.bsutton.sounds
        pluginClass: Sounds
      ios: 
        pluginClass: Sounds

dependency_overrides:
  sounds_common:
    path: ../sounds_common        
